name: makemkv
summary: Backup your Bluray and DVD discs
description: |
  Backup your Bluray and DVD discs
grade: stable
confinement: strict
adopt-info: makemkv-bin
base: core24
compression: lzo
icon: snap/gui/makemkv.png

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
    
apps:
  makemkv:
    command: usr/bin/makemkv
    extensions:
      - kde-neon
    plugs:
      - gsettings
      - hardware-observe
      - home
      - network
      - opengl
      - process-control
      - removable-media
      - desktop
  
  makemkvcon:
    command: usr/bin/makemkvcon 
    plugs:
      - hardware-observe
      - home
      - network
      - process-control
      - removable-media         

parts:
  makemkv-bin:
    plugin: nil
    source: https://www.makemkv.com/download/makemkv-bin-1.18.2.tar.gz
    override-build: |      
      mkdir -p $CRAFT_PART_INSTALL/usr/bin/
      
      # oss
      wget https://www.makemkv.com/download/makemkv-oss-1.18.2.tar.gz
      tar -xvzf makemkv-oss-1.18.2.tar.gz
      cd makemkv-oss-1.18.2/
      ./configure
      make
      make install
      
      # bin
      wget https://www.makemkv.com/download/makemkv-bin-1.18.2.tar.gz
      tar -xvzf makemkv-bin-1.18.2.tar.gz
      cd makemkv-bin-1.18.2/
      mkdir tmp && touch tmp/eula_accepted
      make
      make install 

      ls -al $CRAFT_PART_INSTALL/usr/bin
      
    override-pull: |
      VERSION="$(curl --silent --show-error --location \
        'https://www.makemkv.com/forum/viewtopic.php?f=3&t=224' \
        | grep -E 'https?://www.makemkv.com/download/makemkv-bin-[0-9]+\.[0-9]+\.[0-9]+\.tar\.gz' \
        | head -n1 | sed -E -e \
          's|^.*\"https?://www.makemkv.com/download/makemkv-bin-([0-9]+\.[0-9]+\.[0-9]+)\.tar\.gz\".*|\1|')"
      echo "Setting snap version to '$VERSION'"
      craftctl set version="$VERSION"
      echo "$VERSION" > "$SNAPCRAFT_PROJECT_DIR/version"      
           
    build-packages:
      - build-essential 
      - pkg-config
      - libc6-dev 
      - libssl-dev 
      - libexpat1-dev 
      - libavcodec-dev 
      - libgl1-mesa-dev 
      - qtbase5-dev 
      - zlib1g-dev
      - wget
 
    stage-packages:
      - libavutil-dev
      - ffmpeg
      - libavcodec-dev                      
